<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Title>EventBus.RabbitMQ</Title>
        <Authors>MirolimMajidov</Authors>
        <Description>It's easier to implement EventBus with RabbitMQ to publish and receive events. It is designed to work with multiple virtual hosts.</Description>
        <PackageProjectUrl>https://github.com/MirolimMajidov/EventMessaging</PackageProjectUrl>
        <RepositoryUrl>https://github.com/MirolimMajidov/EventMessaging</RepositoryUrl>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageTags>EventBus.RabbitMQ, RabbitMQ, EventBus</PackageTags>
        <Company>Alif Capital</Company>
        <NeutralLanguage>en</NeutralLanguage>
        <PackageId>Mirolim.EventBus.RabbitMQ</PackageId>
        <AssemblyName>Mirolim.EventBus.RabbitMQ</AssemblyName>
        <Version>9.0.16</Version>
    </PropertyGroup>

    <ItemGroup>
<!--        <PackageReference Include="Mirolim.EventStorage" Version="9.0.15" />-->
        <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="9.0.6" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.6" />
        <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.6" />
        <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="9.0.6" />
        <PackageReference Include="OpenTelemetry" Version="1.12.0" />
        <PackageReference Include="RabbitMQ.Client" Version="6.8.1" />
        <PackageReference Include="Polly" Version="8.6.1" />
    </ItemGroup>

    <ItemGroup>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
            <_Parameter1>EventBus.RabbitMQ.Tests</_Parameter1>
        </AssemblyAttribute>
        <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\EventStorage\EventStorage.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Include="README.md" Pack="true" PackagePath="" />
    </ItemGroup>

</Project>
